'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DDCounter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1719a761587fd6ad865831e489ae21d38f46dfa7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1719a761587fd6ad865831e489ae21d38f46dfa7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aXIS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aXIS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blackwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blackwhite1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackwhite1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blackwhite2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackwhite2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Budget_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Budget-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Buy_now_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buy-now-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cara_Mengaktifkan_Paket_Internet_HotRod_3G__Triple_Kuota_XL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cara-Mengaktifkan-Paket-Internet-HotRod-3G+-Triple-Kuota-XL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ceria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ceria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property indosat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indosat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kartu_GSM_three() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kartu GSM three", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_demo_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo-demo-orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_esia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo esia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_hepi_magenta1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo-hepi_magenta1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LOGO_PLN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGO PLN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo_smartfren() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo-smartfren", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lowongan_kerja_telkom_flexi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lowongan kerja telkom flexi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lowongan_kerja_telkom_flexi1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lowongan kerja telkom flexi1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notification_done() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notification_done", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notification_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notification_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notification_warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notification_warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paket_blackberry_xl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paket-blackberry-xl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starone_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starone_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Telkomsel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Telkomsel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
